Support a standard go path by using "go env GOPATH"
vroomy/plugins pull request #19
Opened 2020-08-25 02:18 UTC by djeebus

Also cache it for faster repeat lookups

2020-08-31 17:32 UTC, dhalman commented on utils.go
> +var goPath = ""
@djeebus we usually do globals at the top (if we can't avoid them)

Also, we try to do named return values 
`getGoPath() (goPath string, err error)`

Then set those values upon return

```
if len(cachedGoPath) > 0 {
   goPath = cachedGoPath
} else {
   // Parse goPath
   ...
   if err != nil {
      return
   }
}

return
```

2020-08-31 17:47 UTC, itsmontoya requested changes
Left some notes!

2020-08-31 17:47 UTC, itsmontoya commented on utils.go
> +	gitfetch.Dir, err = getGitDir(gitURL)
```go
if gitfetch.Dir, err = getGitDir(gitURL); err != nil {
   err = fmt.Errorf("error getting git directory for URL \"%s\": %v", gitURL, err)
   return
}
```

2020-08-31 17:47 UTC, itsmontoya commented on utils.go
> +	gitfetch.Dir, err = getGitDir(gitURL)
Also, add newline before `gitfetch.Stdin = os.Stdin`

2020-08-31 17:47 UTC, itsmontoya commented on utils.go
> +	gitcheckout.Dir, err = getGitDir(gitURL)
```go
if gitcheckout.Dir, err = getGitDir(gitURL); err != nil {
   err = fmt.Errorf("error getting git directory for URL \"%s\": %v", gitURL, err)
   return
}
```

2020-08-31 17:47 UTC, itsmontoya commented on utils.go
> +	gitpull.Dir, err = getGitDir(gitURL)
```go
if gitpull.Dir, err = getGitDir(gitURL); err != nil {
   err = fmt.Errorf("error getting git directory for URL \"%s\": %v", gitURL, err)
   return
}
```

2020-08-31 17:47 UTC, itsmontoya commented on utils.go
> +	update.Dir, err = getGoDir(gitURL)
```go
if update.Dir, err = getGitDir(gitURL); err != nil {
   err = fmt.Errorf("error getting git directory for URL \"%s\": %v", gitURL, err)
   return
}
```

2020-09-04 21:27 UTC, dhalman commented
@djeebus @itsmontoya are we still planning on getting this updated and merged?

2020-09-06 05:41 UTC, djeebus commented
Just noticed the new comments. I'll get them sorted out soon.

2020-09-08 15:02 UTC, djeebus commented
Ok, comments resolved.

2020-09-08 19:20 UTC, dhalman commented on utils.go
> +		goPath = cachedGoPath
I'd remove line 431 and move this to before the final return statement (outside the conditional)

2022-03-31 20:02 UTC, closed without merging